// Mocks generated by Mockito 5.4.6 from annotations
// in music_library/test/downloader_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:music_library/database/database_helper.dart' as _i4;
import 'package:music_library/models/track.dart' as _i6;
import 'package:music_library/models/user_settings.dart' as _i7;
import 'package:music_library/utils/process_manager.dart' as _i8;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProcess_1 extends _i1.SmartFake implements _i3.Process {
  _FakeProcess_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSink_2 extends _i1.SmartFake implements _i3.IOSink {
  _FakeIOSink_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i4.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<bool> trackExists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #trackExists,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> insertTrack(_i6.Track? track) => (super.noSuchMethod(
        Invocation.method(
          #insertTrack,
          [track],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.UserSettings?> getUserSettings() => (super.noSuchMethod(
        Invocation.method(
          #getUserSettings,
          [],
        ),
        returnValue: _i5.Future<_i7.UserSettings?>.value(),
      ) as _i5.Future<_i7.UserSettings?>);
}

/// A class which mocks [ProcessManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcessManager extends _i1.Mock implements _i8.ProcessManager {
  MockProcessManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Process> start(
    String? executable,
    List<String>? arguments, {
    String? workingDirectory,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #start,
          [
            executable,
            arguments,
          ],
          {#workingDirectory: workingDirectory},
        ),
        returnValue: _i5.Future<_i3.Process>.value(_FakeProcess_1(
          this,
          Invocation.method(
            #start,
            [
              executable,
              arguments,
            ],
            {#workingDirectory: workingDirectory},
          ),
        )),
      ) as _i5.Future<_i3.Process>);

  @override
  _i5.Future<_i3.ProcessResult> run(
    String? executable,
    List<String>? arguments, {
    String? workingDirectory,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #run,
          [
            executable,
            arguments,
          ],
          {#workingDirectory: workingDirectory},
        ),
        returnValue: _i5.Future<_i3.ProcessResult>.value(
            _i9.dummyValue<_i3.ProcessResult>(
          this,
          Invocation.method(
            #run,
            [
              executable,
              arguments,
            ],
            {#workingDirectory: workingDirectory},
          ),
        )),
      ) as _i5.Future<_i3.ProcessResult>);
}

/// A class which mocks [Process].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcess extends _i1.Mock implements _i3.Process {
  MockProcess() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> get exitCode => (super.noSuchMethod(
        Invocation.getter(#exitCode),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Stream<List<int>> get stdout => (super.noSuchMethod(
        Invocation.getter(#stdout),
        returnValue: _i5.Stream<List<int>>.empty(),
      ) as _i5.Stream<List<int>>);

  @override
  _i5.Stream<List<int>> get stderr => (super.noSuchMethod(
        Invocation.getter(#stderr),
        returnValue: _i5.Stream<List<int>>.empty(),
      ) as _i5.Stream<List<int>>);

  @override
  _i3.IOSink get stdin => (super.noSuchMethod(
        Invocation.getter(#stdin),
        returnValue: _FakeIOSink_2(
          this,
          Invocation.getter(#stdin),
        ),
      ) as _i3.IOSink);

  @override
  int get pid => (super.noSuchMethod(
        Invocation.getter(#pid),
        returnValue: 0,
      ) as int);

  @override
  bool kill([_i3.ProcessSignal? signal = _i3.ProcessSignal.sigterm]) =>
      (super.noSuchMethod(
        Invocation.method(
          #kill,
          [signal],
        ),
        returnValue: false,
      ) as bool);
}
